# 开发环境配置

# 配置mysql数据源
spring:
  datasource:
    # 用户名
    username: root
    # 密码
    password: 806823
    # mysql的连接路径
    url: jdbc:mysql://localhost:3306/health?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    # 配置驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis相关配置
  redis:
    # 配置主机
    host: 127.0.0.1
    # 配置使用的数据库
    database: 0
    # 指定端口
    port: 6379
  # 邮件配置
  mail:
    # smtp服务主机(163) QQ：smtp.qq.com
    host: smtp.qq.com
    # 服务协议
    protocol: smtp
    # 设置编码集
    default-encoding: UTF-8
    # 允许测试连接
    test-connection: true
    # 设置发件人
    username: 2300858713@qq.com
    # 授权码
    password: atrdavqvptfnebbe
    # 服务端口
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
            required: true
